### ISSUE TITLE
Transparancy

### ISSUE THREAD

**Issue by NielsPilgaard** [Lykrast/Turf#1]
Hello o/

I've been using Slab Turf blocks around a farm, and whenever I harvest the items frequently land inside/under the Turf Slabs, which makes me wonder if they're transparent - And whether they should or shouldn't be?

**Comment by Lykrast** [comment]
I think you meant like intangible/non solid rather than transparent. Either way they're supposed to act exactly like slabs and nothing in the code would make them behave differently.

Try the same setup with vanilla slabs and see if the issue is there.

**Comment by NielsPilgaard** [comment]
Alright, thank you.
