### ISSUE TITLE
Can't dye the turf

### ISSUE THREAD

**Issue by ZellieMoogle** [Lykrast/Turf#2]
Hi :) I have the Enigmatica 4 (0.5.4) modpack installed, and I can make turf without a problem, but the crafting recipe to dye the turf doesn't work. I've noticed that the modpack comes up with two versions of the turf item, one is from your Turf mod and one is from Quark. It seems to be making the Quark one, which has no dye recipes, but both turfs use the exact same materials and it won't let me pick the Turf mod turf - even if I click the Turf mod turf in the search bar it still makes the Quark one.

Do you have any ideas on how to get past this? I really want to make the dyed turfs that your mod uses :)

**Comment by Lykrast** [comment]
This seems to be an issue with the modpack and not the mods, please report this to the Enigmatica 4 issue tracker so they can fix it with recipe changes.
